apiVersion: v1
kind: ConfigMap
metadata:
  name: sentiment-api-config
  labels:
    app: sentiment-api
data:
  app_name: "Sentiment Analysis API"
  log_level: "INFO"
  model_path: "/app/models/sentiment_model.joblib"
